name: map_tracking_repository
description: Dart package which manages the connection to the mongodb.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^3.1.0
dependencies:
  mongo_dart: ^0.9.1
  realm: ^1.0.3
